### ISSUE TITLE
Throws `attempted to get private field on non-instance` error

### ISSUE THREAD

**Issue by towerhe** [Gavant/orbit-model#4]
When I try to get the related record from a loaded model, I met the following error:

```
    TypeError: attempted to get private field on non-instance

      20 |     identity: RecordIdentity;
      21 | }
    > 22 | export default class Model {
         |                                                                     ^
      23 |     #cache?: Cache;
      24 |     #identity: RecordIdentity;
      25 |

      at _classExtractFieldDescriptor (src/model.ts:22:110)
      at _classPrivateFieldGet (src/model.ts:16:73)
      at Proxy.$getRelatedRecord (src/model.ts:74:31)
      at Object.<anonymous> (test/store.test.ts:131:27)
```

After I changed `this.#identity` in `$getRelatedRecord(...)` to `this.$identity`, It passed. Did I miss something for accessing `this.#identity`, or should we change all `this.#identity` to `this.$identity` ?

**Comment by towerhe** [comment]
The issue could be reproduced in https://github.com/towerhe/orbit-model/tree/reproduce-private-field-access-issue
